package prompt

import (
	"bytes"
	"fmt"
	"text/template"

	"github.com/gabrielassisxyz/kernl/internal/merge"
)

// Child identifies a single bead branch that must be merged into its epic.
type Child struct {
	ID           string
	Branch       string
	WorktreePath string
}

// MergerInput feeds the merger prompt template.
type MergerInput struct {
	EpicID     string
	EpicTitle  string
	EpicBranch string
	BaseBranch string
	Children   []Child
}

const mergerTemplate = `You are the kernl integration agent for epic {{.EpicID}}: "{{.EpicTitle}}".

Your job: merge each child branch into the epic branch in topological order, push, and open a PR.

Inputs:
- epic_branch: {{.EpicBranch}}
- base_branch: {{.BaseBranch}}
- children (ordered):{{range .Children}}
  - {{.ID}}: branch={{.Branch}}, worktree={{.WorktreePath}}
{{end}}
Procedure:
1. cd into the epic worktree (parent of {{.EpicBranch}}). git checkout {{.EpicBranch}}.
2. For each child in the listed order:
   a. git merge --no-ff {{"{{.Branch}}"}}
   b. On conflict: read conflict markers; resolve safely. If you cannot resolve within your follow-up budget, write
      "merge_conflict_at: {{"{{.Branch}}"}}" and "merge_outcome: merge_conflict" to the epic bead description and STOP.
3. After all merges succeed: git push origin {{.EpicBranch}}. Retry 2× with backoff on failure.
   If push still fails: write "merge_outcome: push_failed" and STOP.
4. gh pr create --title "{{.EpicTitle}}" --body <auto-generated summary>.
   - If the error indicates the PR already exists, query gh pr list --head {{.EpicBranch}} --json url,
     write "pr_url: <existing>", write "merge_outcome: pr_already_exists", and STOP.
   - On other gh pr create errors: write "merge_outcome: pr_create_failed" and STOP.
5. On full success: write "pr_url: <new>" and "merge_outcome: success" to the epic bead description and STOP.

The merge_outcome MUST be exactly one of:{{range .Outcomes}}
  - {{.}}
{{end}}
Failure modes you MUST enumerate explicitly to the operator before stopping:
- merge_conflict (intractable conflict in one child)
- push_failed (network/auth/protection rule after merges succeeded locally)
- pr_create_failed (gh pr create failed for a reason other than "PR already exists")
`

type mergerView struct {
	MergerInput
	Outcomes []merge.Outcome
}

var mergerTmpl = template.Must(template.New("merger").Parse(mergerTemplate))

// RenderMerger renders the merger prompt for a given epic and its children.
func RenderMerger(in MergerInput) (string, error) {
	if in.EpicBranch == "" || in.BaseBranch == "" {
		return "", fmt.Errorf("KERNL DISPATCH FAILURE: missing branches in MergerInput — EpicBranch=%q BaseBranch=%q — Fix: populate both branches", in.EpicBranch, in.BaseBranch)
	}
	var buf bytes.Buffer
	if err := mergerTmpl.Execute(&buf, mergerView{MergerInput: in, Outcomes: merge.All()}); err != nil {
		return "", err
	}
	return buf.String(), nil
}
