package prompt_test

import (
	"strings"
	"testing"

	"github.com/gabrielassisxyz/kernl/internal/prompt"
)

func sampleShipmentInput() prompt.ShipmentInput {
	return prompt.ShipmentInput{
		EpicID: "e1", EpicTitle: "Test epic", EpicBranch: "feat/e1", BaseBranch: "master",
		RemoteName: "origin", RemoteURL: "git@github.com:owner/repo.git", RepoSlug: "github.com/owner/repo",
		TrackerCommand: "br --db /repo/.beads/beads.db",
		PRBodyPath:     "/home/agent/.kernl/state/run/e1/e1/pr-body.md",
	}
}

func TestRenderShipment_Content(t *testing.T) {
	out, err := prompt.RenderShipment(sampleShipmentInput())
	if err != nil {
		t.Fatal(err)
	}
	mustContain := []string{
		"git push",
		"gh pr create",
		"--head feat/e1 --json url",
		"pr_already_exists",
		"pr_url:",
		"push_failed",
		"pr_create_failed",
		// The destination is named in the prompt so the agent has nothing to
		// resolve on its own initiative.
		"git push origin feat/e1",
		"git@github.com:owner/repo.git",
		// gh must be pinned to the verified repository: without --repo it picks
		// one out of the working directory's remotes, which is the choice that
		// must not stay open.
		"gh pr create --repo github.com/owner/repo",
		"gh pr list --repo github.com/owner/repo",
	}
	for _, want := range mustContain {
		if !strings.Contains(out, want) {
			t.Errorf("shipment prompt missing %q", want)
		}
	}
}

// A double-quoted shell string does not turn \n into a line break, so an
// agent handed "--body <summary with \n in it>" published a pull request
// description as one line with the escape sequences left in it (archeion PR
// #42). The rendered prompt must route the body through a file instead of a
// shell argument, so the mechanism does not depend on the agent's shell
// dialect getting multi-line quoting right.
func TestRenderShipment_BodyGoesThroughAFileNotAShellArgument(t *testing.T) {
	out, err := prompt.RenderShipment(sampleShipmentInput())
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out, "gh pr create --repo github.com/owner/repo --base master --head feat/e1 --title \"Test epic\" --body-file /home/agent/.kernl/state/run/e1/e1/pr-body.md") {
		t.Errorf("shipment prompt must open the PR with --body-file pointing at the resolved artifact path:\n%s", out)
	}
	if !strings.Contains(out, "Write a summary of the epic and its merged children as the pull request body to this file") {
		t.Errorf("shipment prompt must instruct the agent to write the body to a file before calling gh:\n%s", out)
	}
	if strings.Contains(out, "--body <auto-generated") {
		t.Errorf("shipment prompt must not pass the body inline as a --body argument:\n%s", out)
	}
}

// The "keep any scratch inside the worktree" instruction governs the
// tracker-update command right below it, not the PR body file step 2 just
// told the agent to write outside the worktree. RenderShipment replaces the
// generic stage prompt wholesale, so its own text is the only guidance the
// shipment agent gets - two instructions in the same document that disagree
// about where a file belongs is exactly the incoherence this recipe must not
// contain.
func TestRenderShipment_ScratchInstructionDoesNotContradictTheBodyFileStep(t *testing.T) {
	out, err := prompt.RenderShipment(sampleShipmentInput())
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out, "this does not apply to the pull request body file from step 2, which belongs outside it") {
		t.Errorf("the scratch instruction must scope itself away from the PR body file:\n%s", out)
	}
}

func TestRenderShipment_RefusesWithoutPRBodyPath(t *testing.T) {
	in := sampleShipmentInput()
	in.PRBodyPath = ""
	if _, err := prompt.RenderShipment(in); err == nil {
		t.Error("expected a refusal when PRBodyPath is unset")
	} else if !strings.Contains(err.Error(), "KERNL DISPATCH FAILURE") {
		t.Errorf("expected KERNL DISPATCH FAILURE, got %v", err)
	}
}

// The one command the shipment stage is told to run against the tracker writes
// the pr_url line the exit gate reads. It embedded "bd" and bd's JSON envelope,
// so against a br repository it wrote nothing and the gate saw nothing.
func TestRenderShipment_RecordsThroughTheRepositorysOwnTracker(t *testing.T) {
	out, err := prompt.RenderShipment(sampleShipmentInput())
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(out, "bd update") || strings.Contains(out, "bd show") {
		t.Errorf("the recipe must not name kernl's own tracker:\n%s", out)
	}
	if !strings.Contains(out, "br --db /repo/.beads/beads.db update e1 --description") {
		t.Errorf("the recipe must append through the repository's tracker:\n%s", out)
	}
	// description is absent rather than empty when unset, and `jq -r` would
	// otherwise write the string "null" into the epic's description.
	if !strings.Contains(out, `.[0].description // ""`) {
		t.Errorf("the recipe must tolerate an unset description:\n%s", out)
	}
}

// Shipment runs under claude and codex too, and neither has opencode's
// permission model. Explaining opencode's rejections to them is noise that
// invites an agent to reason about a sandbox it is not in.
func TestRenderShipment_DoesNotExplainAnotherAgentsSandbox(t *testing.T) {
	out, err := prompt.RenderShipment(sampleShipmentInput())
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(out, "opencode") {
		t.Error("the shipment prompt has no dialect and must not name one")
	}
	// The prohibition itself is dialect-neutral and stays.
	if !strings.Contains(out, "/tmp") {
		t.Error("the shipment prompt must still keep scratch files out of /tmp")
	}
}

func TestRenderShipment_EmptyBranches(t *testing.T) {
	cases := []prompt.ShipmentInput{
		{EpicID: "e1", EpicTitle: "x", EpicBranch: "", BaseBranch: "master", RemoteName: "origin", RemoteURL: "u", RepoSlug: "h/o/r"},
		{EpicID: "e1", EpicTitle: "x", EpicBranch: "feat/e1", BaseBranch: "", RemoteName: "origin", RemoteURL: "u", RepoSlug: "h/o/r"},
	}
	for _, in := range cases {
		if _, err := prompt.RenderShipment(in); err == nil {
			t.Errorf("expected error for input %+v", in)
		} else if !strings.Contains(err.Error(), "KERNL DISPATCH FAILURE") {
			t.Errorf("expected KERNL DISPATCH FAILURE, got %v", err)
		}
	}
}

// A shipment prompt without a verified destination must not render at all:
// "push to origin" with origin unresolved is the ambiguity that published a
// pull request nobody asked for.
func TestRenderShipment_RefusesWithoutDestination(t *testing.T) {
	for _, blank := range []func(*prompt.ShipmentInput){
		func(in *prompt.ShipmentInput) { in.RemoteURL = "" },
		func(in *prompt.ShipmentInput) { in.RemoteName = "" },
		// A local-path remote produces no repository slug, so there is nothing
		// to open a pull request on and nothing to pin gh to.
		func(in *prompt.ShipmentInput) { in.RepoSlug = "" },
	} {
		in := sampleShipmentInput()
		blank(&in)
		if _, err := prompt.RenderShipment(in); err == nil {
			t.Errorf("expected a refusal for input %+v", in)
		}
	}
}

// The failure this step exists for: a pull request was opened whose code
// passed every check, and whose body was refused on the spot by a prose gate
// the repository already owned and already ran. kernl cannot intercept the
// text - the agent writes the body AND calls gh - so the instruction to check
// it before publishing is where the failure is actually prevented.
func TestRenderShipment_ChecksThePullRequestTextBeforePublishing(t *testing.T) {
	in := sampleShipmentInput()
	in.PRTextCommand = "bin/slop-guard --stdin 'PR text'"

	out, err := prompt.RenderShipment(in)
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		"bin/slop-guard --stdin 'PR text'",
		// Title and body both: the title is published prose too.
		`{ echo "Test epic"; echo; cat /home/agent/.kernl/state/run/e1/e1/pr-body.md; } | bin/slop-guard --stdin 'PR text'`,
		"Do not run gh until that command exits zero",
		// A refused body is prose, and rewriting prose is never a reason to
		// start editing code.
		"never a reason to touch code",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("shipment prompt missing %q\n---\n%s\n---", want, out)
		}
	}
	// The step must come before the publish, or it is describing something
	// that already happened.
	if strings.Index(out, "bin/slop-guard") > strings.Index(out, "gh pr create") {
		t.Error("the text check is rendered after gh pr create, so it would check text that is already published")
	}
}

// A repository that declares no prose rule gets no step. A rendered step
// naming an empty command is an instruction to run something the agent has to
// invent.
func TestRenderShipment_NoTextCommandRendersNoStep(t *testing.T) {
	out, err := prompt.RenderShipment(sampleShipmentInput())
	if err != nil {
		t.Fatal(err)
	}
	for _, unwanted := range []string{"2b.", "exits zero"} {
		if strings.Contains(out, unwanted) {
			t.Errorf("shipment prompt contains %q for a repository that declares no text gate\n---\n%s\n---", unwanted, out)
		}
	}
}
