package prompt

import (
	"bytes"
	"fmt"
	"text/template"

	"github.com/gabrielassisxyz/kernl/internal/merge"
)

// ShipmentInput feeds the shipment prompt template.
type ShipmentInput struct {
	EpicID     string
	EpicTitle  string
	EpicBranch string
	BaseBranch string
	// RemoteName and RemoteURL are resolved and checked against the allow-list
	// before dispatch, and both appear in the prompt. The word "origin" alone
	// left the destination to be worked out at runtime, and an agent working in
	// a clone whose origin could not serve the instruction resolved it to the
	// public upstream instead.
	RemoteName string
	RemoteURL  string
	// RepoSlug pins gh to a repository. Without --repo, gh picks one from the
	// working directory's remotes, so a verified push and an unverified pull
	// request can land in different repositories from the same stage.
	RepoSlug string
	// TrackerCommand is how this repository's tracker is typed from inside a
	// worktree, store-pinning flags included. The recipe below embedded "bd"
	// and bd's JSON envelope, which is a fact about kernl's own tracker.
	TrackerCommand string
}

const shipmentTemplate = `You are the kernl shipment agent for epic {{.EpicID}}: "{{.EpicTitle}}".

Your job: push the integrated epic branch and open a GitHub PR. The branches are already merged - do NOT re-merge anything.

Inputs:
- epic_branch: {{.EpicBranch}}
- base_branch: {{.BaseBranch}}
- remote: {{.RemoteName}} ({{.RemoteURL}})

The destination is fixed. Push to {{.RemoteName}} and open the pull request on {{.RepoSlug}} and nowhere else. If that remote cannot serve the push, the correct outcome is push_failed: do NOT look for another remote, another upstream, or another repository that could accept it. A push somewhere the operator did not name is a failure even when it succeeds. Every gh command below carries --repo for the same reason: without it gh picks a repository out of the working directory's remotes, and that choice is exactly what must not be left open.

Procedure:
1. git push {{.RemoteName}} {{.EpicBranch}} - retry up to 2 times with backoff on transient failure. If the push still fails, write
   "merge_outcome: push_failed" to the epic bead description (via {{.TrackerCommand}} update) and STOP.
2. gh pr create --repo {{.RepoSlug}} --base {{.BaseBranch}} --head {{.EpicBranch}} --title "{{.EpicTitle}}" --body <auto-generated summary of the epic and its merged children>
3. If gh reports the PR already exists: run
   gh pr list --repo {{.RepoSlug}} --head {{.EpicBranch}} --json url
   to fetch the existing PR URL, then write "pr_url: <url>" and "merge_outcome: pr_already_exists" to the epic bead description and finish (this is success-equivalent).
4. Any other gh error: write "merge_outcome: pr_create_failed" to the epic bead description and STOP.
5. On success: write a line "pr_url: <url>" AND "merge_outcome: success" to the epic bead description, then STOP. The "pr_url:" line is REQUIRED - an exit gate checks the epic description contains "pr_url:".

Recording the result - write to the epic description in a SINGLE command, with NO temporary files under /tmp; keep any scratch inside the worktree. Append to the existing description by reading it inline:
  {{.TrackerCommand}} update {{.EpicID}} --description "$({{.TrackerCommand}} show {{.EpicID}} --json | jq -r '.[0].description // ""')

  pr_url: <url>
  merge_outcome: success"
This is the one place you SHOULD run "{{.TrackerCommand}} update" - it is how the orchestrator's shipment gate observes the PR URL.

The merge_outcome you write MUST be exactly one of the valid shipment outcomes: success, push_failed, pr_create_failed, pr_already_exists. For reference, the full merge_outcome enum is:{{range .Outcomes}}
  - {{.}}
{{end}}`

type shipmentView struct {
	ShipmentInput
	Outcomes []merge.Outcome
}

var shipmentTmpl = template.Must(template.New("shipment").Parse(shipmentTemplate))

// RenderShipment renders the shipment-stage prompt for a given epic.
func RenderShipment(in ShipmentInput) (string, error) {
	if in.EpicBranch == "" || in.BaseBranch == "" {
		return "", fmt.Errorf("KERNL DISPATCH FAILURE: missing branches in ShipmentInput - EpicBranch=%q BaseBranch=%q - Fix: populate both branches", in.EpicBranch, in.BaseBranch)
	}
	// Refusing here rather than rendering "push to ()" keeps the one stage that
	// publishes from ever running without a verified destination.
	if in.TrackerCommand == "" {
		return "", fmt.Errorf("KERNL DISPATCH FAILURE: shipment prompt has no tracker command, so the PR URL the exit gate reads would be written by running nothing - Fix: resolve it with backend.TrackerInvocation before dispatch")
	}
	if in.RemoteName == "" || in.RemoteURL == "" || in.RepoSlug == "" {
		return "", fmt.Errorf("KERNL DISPATCH FAILURE: shipment prompt has no verified destination - RemoteName=%q RemoteURL=%q RepoSlug=%q - Fix: resolve it with shipment.ResolveDestination before dispatch; a destination with no repository slug (a local path remote) cannot be shipped to", in.RemoteName, in.RemoteURL, in.RepoSlug)
	}
	var buf bytes.Buffer
	if err := shipmentTmpl.Execute(&buf, shipmentView{ShipmentInput: in, Outcomes: merge.All()}); err != nil {
		return "", err
	}
	return buf.String(), nil
}
