package prompt

import (
	"bytes"
	"fmt"
	"text/template"

	"github.com/gabrielassisxyz/kernl/internal/merge"
)

// ShipmentInput feeds the shipment prompt template.
type ShipmentInput struct {
	EpicID     string
	EpicTitle  string
	EpicBranch string
	BaseBranch string
}

const shipmentTemplate = `You are the kernl shipment agent for epic {{.EpicID}}: "{{.EpicTitle}}".

Your job: push the integrated epic branch and open a GitHub PR. The branches are already merged — do NOT re-merge anything.

Inputs:
- epic_branch: {{.EpicBranch}}
- base_branch: {{.BaseBranch}}

Procedure:
1. git push origin {{.EpicBranch}} — retry up to 2 times with backoff on transient failure. If the push still fails, write
   "merge_outcome: push_failed" to the epic bead description (via bd update) and STOP.
2. gh pr create --base {{.BaseBranch}} --head {{.EpicBranch}} --title "{{.EpicTitle}}" --body <auto-generated summary of the epic and its merged children>
3. If gh reports the PR already exists: run
   gh pr list --head {{.EpicBranch}} --json url
   to fetch the existing PR URL, then write "pr_url: <url>" and "merge_outcome: pr_already_exists" to the epic bead description and finish (this is success-equivalent).
4. Any other gh error: write "merge_outcome: pr_create_failed" to the epic bead description and STOP.
5. On success: write a line "pr_url: <url>" AND "merge_outcome: success" to the epic bead description, then STOP. The "pr_url:" line is REQUIRED — an exit gate checks the epic description contains "pr_url:".

Recording the result — write to the epic description in a SINGLE command, with NO temporary files under /tmp (opencode auto-rejects /tmp writes; keep any scratch inside the worktree). Append to the existing description by reading it inline:
  bd update {{.EpicID}} -d "$(bd show {{.EpicID}} --json | jq -r '.[0].description')

  pr_url: <url>
  merge_outcome: success"
This is the one place you SHOULD run "bd update" — it is how the orchestrator's shipment gate observes the PR URL.

The merge_outcome you write MUST be exactly one of the valid shipment outcomes: success, push_failed, pr_create_failed, pr_already_exists. For reference, the full merge_outcome enum is:{{range .Outcomes}}
  - {{.}}
{{end}}`

type shipmentView struct {
	ShipmentInput
	Outcomes []merge.Outcome
}

var shipmentTmpl = template.Must(template.New("shipment").Parse(shipmentTemplate))

// RenderShipment renders the shipment-stage prompt for a given epic.
func RenderShipment(in ShipmentInput) (string, error) {
	if in.EpicBranch == "" || in.BaseBranch == "" {
		return "", fmt.Errorf("KERNL DISPATCH FAILURE: missing branches in ShipmentInput — EpicBranch=%q BaseBranch=%q — Fix: populate both branches", in.EpicBranch, in.BaseBranch)
	}
	var buf bytes.Buffer
	if err := shipmentTmpl.Execute(&buf, shipmentView{ShipmentInput: in, Outcomes: merge.All()}); err != nil {
		return "", err
	}
	return buf.String(), nil
}
